CREATE TABLE IF NOT EXISTS album (
	id SERIAL PRIMARY KEY,
	title VARCHAR(60) NOT NULL,
	year DATE CONSTRAINT (year > 2003)
);

CREATE TABLE IF NOT EXISTS musican (
	id SERIAL PRIMARY KEY,
	name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS MusicalAlbum (
	id SERIAL PRIMARY KEY,
	musican_id INTEGER NOT NULL REFERENCES musican(id),
	album INTEGER NOT NULL REFERENCES album(id)
);

CREATE TABLE IF NOT EXISTS genre (
	id SERIAL PRIMARY KEY,
	name VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS MusicanGenre (
	id SERIAL PRIMARY KEY,
	musican_id INTEGER NOT NULL REFERENCES musican(id),
	genre_id INTEGER NOT NULL REFERENCES genre(id)
);

CREATE TABLE IF NOT EXISTS track (
	id SERIAL PRIMARY KEY,
	name VARCHAR(10) NOT NULL,
	time INTEGER CONSTRAINT (time > 0:30),
	album VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS collection (
	id SERIAL PRIMARY KEY,
	name VARCHAR(10) NOT NULL,
	year_of_release DATE CONSTRAINT (year > 2003),
);